# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version=1.6-26.1.x
maven_group=me.micahcode
archives_base_name=hqtiers

fabric_version=0.145.1+26.1
clothConfig=26.1.154
modMenu=18.0.0-alpha.8
loom_version=1.17-SNAPSHOT