# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=4.0-26.3
maven_group=me.micahcode
archives_base_name=hqtiers

fabric_version=0.160.5+26.3
clothConfig=26.3.159
modMenu=21.0.0
loom_version=1.17-SNAPSHOT